// @ts-nocheck
import * as __fd_glob_66 from "../content/docs/ui/manual-installation/next.mdx?collection=docs"
import * as __fd_glob_65 from "../content/docs/api-reference/webhookVirtualAccountTransactionSettled.mdx?collection=docs"
import * as __fd_glob_64 from "../content/docs/api-reference/webhookVirtualAccountTransaction.mdx?collection=docs"
import * as __fd_glob_63 from "../content/docs/api-reference/webhookVirtualAccountRejectedTransaction.mdx?collection=docs"
import * as __fd_glob_62 from "../content/docs/api-reference/webhookTransactionSuccessful.mdx?collection=docs"
import * as __fd_glob_61 from "../content/docs/api-reference/webhookTransactionFailed.mdx?collection=docs"
import * as __fd_glob_60 from "../content/docs/api-reference/webhookPOSTransactionSettled.mdx?collection=docs"
import * as __fd_glob_59 from "../content/docs/api-reference/webhookPOSTransaction.mdx?collection=docs"
import * as __fd_glob_58 from "../content/docs/api-reference/webhookPOSTerminalUpdated.mdx?collection=docs"
import * as __fd_glob_57 from "../content/docs/api-reference/webhookBillPaymentSuccessful.mdx?collection=docs"
import * as __fd_glob_56 from "../content/docs/api-reference/webhookBillPaymentFailed.mdx?collection=docs"
import * as __fd_glob_55 from "../content/docs/api-reference/webhookAccountBalanceUpdated.mdx?collection=docs"
import * as __fd_glob_54 from "../content/docs/api-reference/unassignPOSTerminal.mdx?collection=docs"
import * as __fd_glob_53 from "../content/docs/api-reference/resolveAccount.mdx?collection=docs"
import * as __fd_glob_52 from "../content/docs/api-reference/repushPOSTransactionWebhook.mdx?collection=docs"
import * as __fd_glob_51 from "../content/docs/api-reference/lookupBillAccount.mdx?collection=docs"
import * as __fd_glob_50 from "../content/docs/api-reference/listVirtualAccountsTransactions.mdx?collection=docs"
import * as __fd_glob_49 from "../content/docs/api-reference/listVirtualAccountTransactions.mdx?collection=docs"
import * as __fd_glob_48 from "../content/docs/api-reference/listTransactions.mdx?collection=docs"
import * as __fd_glob_47 from "../content/docs/api-reference/listStaticVirtualAccounts.mdx?collection=docs"
import * as __fd_glob_46 from "../content/docs/api-reference/listRejectedVirtualAccountTransactions.mdx?collection=docs"
import * as __fd_glob_45 from "../content/docs/api-reference/listRecipients.mdx?collection=docs"
import * as __fd_glob_44 from "../content/docs/api-reference/listPOSTransactions.mdx?collection=docs"
import * as __fd_glob_43 from "../content/docs/api-reference/listPOSTerminals.mdx?collection=docs"
import * as __fd_glob_42 from "../content/docs/api-reference/listBills.mdx?collection=docs"
import * as __fd_glob_41 from "../content/docs/api-reference/listBillVendorsByCategory.mdx?collection=docs"
import * as __fd_glob_40 from "../content/docs/api-reference/listBillVendors.mdx?collection=docs"
import * as __fd_glob_39 from "../content/docs/api-reference/listBillProductsByVendor.mdx?collection=docs"
import * as __fd_glob_38 from "../content/docs/api-reference/listBillProductsByCategory.mdx?collection=docs"
import * as __fd_glob_37 from "../content/docs/api-reference/listBillProducts.mdx?collection=docs"
import * as __fd_glob_36 from "../content/docs/api-reference/listBillPayments.mdx?collection=docs"
import * as __fd_glob_35 from "../content/docs/api-reference/listAllVirtualAccountTransactions.mdx?collection=docs"
import * as __fd_glob_34 from "../content/docs/api-reference/listAllRejectedVirtualAccountTransactions.mdx?collection=docs"
import * as __fd_glob_33 from "../content/docs/api-reference/getVirtualAccountTransactionById.mdx?collection=docs"
import * as __fd_glob_32 from "../content/docs/api-reference/getVirtualAccountByReference.mdx?collection=docs"
import * as __fd_glob_31 from "../content/docs/api-reference/getVirtualAccountByBvn.mdx?collection=docs"
import * as __fd_glob_30 from "../content/docs/api-reference/getVirtualAccountByAccountReference.mdx?collection=docs"
import * as __fd_glob_29 from "../content/docs/api-reference/getTransferByReference.mdx?collection=docs"
import * as __fd_glob_28 from "../content/docs/api-reference/getTransactionByReference.mdx?collection=docs"
import * as __fd_glob_27 from "../content/docs/api-reference/getTransactionById.mdx?collection=docs"
import * as __fd_glob_26 from "../content/docs/api-reference/getStaticVirtualAccountByBvn.mdx?collection=docs"
import * as __fd_glob_25 from "../content/docs/api-reference/getRejectedVirtualAccountTransactionByIdGlobal.mdx?collection=docs"
import * as __fd_glob_24 from "../content/docs/api-reference/getRejectedVirtualAccountTransactionById.mdx?collection=docs"
import * as __fd_glob_23 from "../content/docs/api-reference/getRecipientById.mdx?collection=docs"
import * as __fd_glob_22 from "../content/docs/api-reference/getPOSTransactionByReference.mdx?collection=docs"
import * as __fd_glob_21 from "../content/docs/api-reference/getPOSTransactionById.mdx?collection=docs"
import * as __fd_glob_20 from "../content/docs/api-reference/getPOSTerminalById.mdx?collection=docs"
import * as __fd_glob_19 from "../content/docs/api-reference/getBulkTransferByReference.mdx?collection=docs"
import * as __fd_glob_18 from "../content/docs/api-reference/getBillVendorById.mdx?collection=docs"
import * as __fd_glob_17 from "../content/docs/api-reference/getBillProductById.mdx?collection=docs"
import * as __fd_glob_16 from "../content/docs/api-reference/getBillPaymentByReference.mdx?collection=docs"
import * as __fd_glob_15 from "../content/docs/api-reference/getBillPaymentById.mdx?collection=docs"
import * as __fd_glob_14 from "../content/docs/api-reference/getBillByReference.mdx?collection=docs"
import * as __fd_glob_13 from "../content/docs/api-reference/getBillById.mdx?collection=docs"
import * as __fd_glob_12 from "../content/docs/api-reference/getBanks.mdx?collection=docs"
import * as __fd_glob_11 from "../content/docs/api-reference/getAccounts.mdx?collection=docs"
import * as __fd_glob_10 from "../content/docs/api-reference/getAccountById.mdx?collection=docs"
import * as __fd_glob_9 from "../content/docs/api-reference/getAccountBalance.mdx?collection=docs"
import * as __fd_glob_8 from "../content/docs/api-reference/createVirtualAccount.mdx?collection=docs"
import * as __fd_glob_7 from "../content/docs/api-reference/createTransfer.mdx?collection=docs"
import * as __fd_glob_6 from "../content/docs/api-reference/createTransaction.mdx?collection=docs"
import * as __fd_glob_5 from "../content/docs/api-reference/createRecipient.mdx?collection=docs"
import * as __fd_glob_4 from "../content/docs/api-reference/createBulkTransfers.mdx?collection=docs"
import * as __fd_glob_3 from "../content/docs/api-reference/createBillPayment.mdx?collection=docs"
import * as __fd_glob_2 from "../content/docs/api-reference/createBill.mdx?collection=docs"
import * as __fd_glob_1 from "../content/docs/api-reference/assignPOSTerminal.mdx?collection=docs"
import { default as __fd_glob_0 } from "../content/docs/api-reference/meta.json?collection=docs"
import { server } from 'fumadocs-mdx/runtime/server';
import type * as Config from '../source.config';

const create = server<typeof Config, import("fumadocs-mdx/runtime/types").InternalTypeConfig & {
  DocData: {
  }
}>({"doc":{"passthroughs":["extractedReferences"]}});

export const docs = await create.docs("docs", "content/docs", {"api-reference/meta.json": __fd_glob_0, }, {"api-reference/assignPOSTerminal.mdx": __fd_glob_1, "api-reference/createBill.mdx": __fd_glob_2, "api-reference/createBillPayment.mdx": __fd_glob_3, "api-reference/createBulkTransfers.mdx": __fd_glob_4, "api-reference/createRecipient.mdx": __fd_glob_5, "api-reference/createTransaction.mdx": __fd_glob_6, "api-reference/createTransfer.mdx": __fd_glob_7, "api-reference/createVirtualAccount.mdx": __fd_glob_8, "api-reference/getAccountBalance.mdx": __fd_glob_9, "api-reference/getAccountById.mdx": __fd_glob_10, "api-reference/getAccounts.mdx": __fd_glob_11, "api-reference/getBanks.mdx": __fd_glob_12, "api-reference/getBillById.mdx": __fd_glob_13, "api-reference/getBillByReference.mdx": __fd_glob_14, "api-reference/getBillPaymentById.mdx": __fd_glob_15, "api-reference/getBillPaymentByReference.mdx": __fd_glob_16, "api-reference/getBillProductById.mdx": __fd_glob_17, "api-reference/getBillVendorById.mdx": __fd_glob_18, "api-reference/getBulkTransferByReference.mdx": __fd_glob_19, "api-reference/getPOSTerminalById.mdx": __fd_glob_20, "api-reference/getPOSTransactionById.mdx": __fd_glob_21, "api-reference/getPOSTransactionByReference.mdx": __fd_glob_22, "api-reference/getRecipientById.mdx": __fd_glob_23, "api-reference/getRejectedVirtualAccountTransactionById.mdx": __fd_glob_24, "api-reference/getRejectedVirtualAccountTransactionByIdGlobal.mdx": __fd_glob_25, "api-reference/getStaticVirtualAccountByBvn.mdx": __fd_glob_26, "api-reference/getTransactionById.mdx": __fd_glob_27, "api-reference/getTransactionByReference.mdx": __fd_glob_28, "api-reference/getTransferByReference.mdx": __fd_glob_29, "api-reference/getVirtualAccountByAccountReference.mdx": __fd_glob_30, "api-reference/getVirtualAccountByBvn.mdx": __fd_glob_31, "api-reference/getVirtualAccountByReference.mdx": __fd_glob_32, "api-reference/getVirtualAccountTransactionById.mdx": __fd_glob_33, "api-reference/listAllRejectedVirtualAccountTransactions.mdx": __fd_glob_34, "api-reference/listAllVirtualAccountTransactions.mdx": __fd_glob_35, "api-reference/listBillPayments.mdx": __fd_glob_36, "api-reference/listBillProducts.mdx": __fd_glob_37, "api-reference/listBillProductsByCategory.mdx": __fd_glob_38, "api-reference/listBillProductsByVendor.mdx": __fd_glob_39, "api-reference/listBillVendors.mdx": __fd_glob_40, "api-reference/listBillVendorsByCategory.mdx": __fd_glob_41, "api-reference/listBills.mdx": __fd_glob_42, "api-reference/listPOSTerminals.mdx": __fd_glob_43, "api-reference/listPOSTransactions.mdx": __fd_glob_44, "api-reference/listRecipients.mdx": __fd_glob_45, "api-reference/listRejectedVirtualAccountTransactions.mdx": __fd_glob_46, "api-reference/listStaticVirtualAccounts.mdx": __fd_glob_47, "api-reference/listTransactions.mdx": __fd_glob_48, "api-reference/listVirtualAccountTransactions.mdx": __fd_glob_49, "api-reference/listVirtualAccountsTransactions.mdx": __fd_glob_50, "api-reference/lookupBillAccount.mdx": __fd_glob_51, "api-reference/repushPOSTransactionWebhook.mdx": __fd_glob_52, "api-reference/resolveAccount.mdx": __fd_glob_53, "api-reference/unassignPOSTerminal.mdx": __fd_glob_54, "api-reference/webhookAccountBalanceUpdated.mdx": __fd_glob_55, "api-reference/webhookBillPaymentFailed.mdx": __fd_glob_56, "api-reference/webhookBillPaymentSuccessful.mdx": __fd_glob_57, "api-reference/webhookPOSTerminalUpdated.mdx": __fd_glob_58, "api-reference/webhookPOSTransaction.mdx": __fd_glob_59, "api-reference/webhookPOSTransactionSettled.mdx": __fd_glob_60, "api-reference/webhookTransactionFailed.mdx": __fd_glob_61, "api-reference/webhookTransactionSuccessful.mdx": __fd_glob_62, "api-reference/webhookVirtualAccountRejectedTransaction.mdx": __fd_glob_63, "api-reference/webhookVirtualAccountTransaction.mdx": __fd_glob_64, "api-reference/webhookVirtualAccountTransactionSettled.mdx": __fd_glob_65, "ui/manual-installation/next.mdx": __fd_glob_66, });